### ISSUE TITLE
XML-API & Firefox II Internet Explorer

### ISSUE THREAD

**Issue by roe1974** [homematic-community/XML-API#17]
Hi

Gibt es einen Weg die XML-API Informationen im Firefox zum laufen zu bekommen ?

Muss hier immer auf den IE ausweichen...und der zeigt nicht alles an (zB. rssilist.cgi)

Firefox Quantum 61.0.2 64Bit

lg Richard

**Comment by jens-maus** [comment]
Nur weil der Firefox nicht standardmäßig XML daten als tree darstellt heisst das nicht das die XML-API nicht funktioniert. Einfach den Quelltext der seite anzeigen lassen und man sieht ihn auch in Firefox&Co.

**Comment by HolgerJeromin** [comment]
Which BTW was fixed. At least my 447kByte `/addons/xmlapi/statelist.cgi` is shown as a full interactive tree in Firefox 118.
