### ISSUE TITLE
OSRAM Lightify 'VIR-OL-GTW OL-Lightify-01' LEVEL wird im Status nicht wiedergespiegelt

### ISSUE THREAD

**Issue by michl-b** [homematic-community/XML-API#18]
Wenn man an einer Osram Lightify das Dimmer LEVEL value setzt. Spricht die Lampe korrekt an, aber im Status wird weiterhin der LEVEL 0.000000 geliefert.

Gerät: VIR-OL-GTW OL-Lightify-01
Zentrale: homematic-raspi
XMLAPI-Version: 1.18

XML-Infos:
```xml
Device:
<device name="VIR-OL-GTW OL-Lightify-01" address="OL-Lightify-01" ise_id="1334" interface="VirtualDevices" device_type="VIR-OL-GTW" ready_config="true">
<channel name="VIR-OL-GTW OL-Lightify-01:0" type="30" address="OL-Lightify-01:0" ise_id="1335" direction="UNKNOWN" parent_device="1334" index="0" group_partner="" aes_available="false" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="VIR-OL-GTW OL-Lightify-01:1" type="17" address="OL-Lightify-01:1" ise_id="1336" direction="UNKNOWN" parent_device="1334" index="1" group_partner="" aes_available="false" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
</device>


Status:
<device name="VIR-OL-GTW OL-Lightify-01" ise_id="1334">
<channel name="VIR-OL-GTW OL-Lightify-01:0" ise_id="1335" index="0" visible="true" operate="true"/>
<channel name="VIR-OL-GTW OL-Lightify-01:1" ise_id="1336" index="1" visible="true" operate="true">
<datapoint name="VirtualDevices.OL-Lightify-01:1.LEVEL" type="LEVEL" ise_id="1337" value="0.000000" valuetype="4" valueunit="100%" timestamp="1535804763" operations="3"/>
</channel>
</device>
```

Befehle: 
- State: `http://homematic-raspi/addons/xmlapi/state.cgi?datapoint_id=1341`
- Change: `http://homematic-raspi/addons/xmlapi/statechange.cgi?ise_id=1341&new_value=0.500000` => State liefert weiterhin 0.000000

**Comment by jens-maus** [comment]
@Monty1979 Stell diese Informationen hier rein und ich werde mit eQ3 reden.

**Comment by Monty1979** [comment]
über die Locale Lightify API kann man die Werte einfach abfragen mit

`			byte[] array = { 0x0B, 0x00, 0x00, 0x13, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00 };
			ByteBuffer data = ByteBuffer.allocate(array.length);
			data.put(array);

			send(data);
			data = recv();

			int num = data.getShort(9);

			for (int i = 0; i < num; i++) {
				// ?
				int pos = 11 + i * 50;

				OsramDeviceVO device = new OsramDeviceVO();
				ByteBuffer payload = byteBufferWrap(data.array(), pos, 50);
				byte[] b = new byte[50];
				payload.get(b);


				// 01 - ID Teil 1
				payload.position(pos + 0);
				byte id1 = payload.get();
				String id1S = IO.hexToBin(IO.byteToHex(id1));

				// 02 ID Teil 2
				payload.position(pos + 1);
				byte id2 = payload.get();
				String id2S = id1S + IO.hexToBin(IO.byteToHex(id2));
				device.setDeviceId(Integer.parseInt(id2S, 2));

				// 02-08 Mac
				byte[] mac = new byte[8];
				payload.position(pos + 2);
				payload.get(mac);
				device.setMacAddress(mac);

				// 10 - Bulb Type ???
				payload.position(pos + 10);
				int lightType = payload.get();
				device.setDeviceType("" + lightType);

				// 11-14 Firmenware
				byte[] fw = new byte[5];
				payload.position(pos + 11);
				payload.get(fw);
				device.setFirmwareVersion(toHexString(fw));

				// 15 - Online/Offline
				payload.position(pos + 15);
				int onlineStatus = payload.get();
				device.setOnline(onlineStatus);

				// 18 - Status 0 == off, 1 == on
				payload.position(pos + 18);
				int on = payload.get();
				device.setOn(on);

				// 19 - Brightness (0-100)
				payload.position(pos + 19);				
				int brightness = payload.get();
				device.setBrightnessLevel(brightness);
				
				// 20 - Temperature 1
				payload.position(pos + 20);
				short temp = payload.getShort();
				device.setTemperature((int) temp);

				// 21 - Temperature 2 ???
				payload.position(pos + 21);
				byte temp2 = payload.get();

				// 22 - R
				payload.position(pos + 22);
				byte red = payload.get();
				String redS = IO.byteToHex(red);

				// 23 - G
				payload.position(pos + 23);
				byte green = payload.get();
				String greenS = IO.byteToHex(green);

				// 24 - B
				payload.position(pos + 24);
				byte blue = payload.get();
				String blueS = IO.byteToHex(blue);

				// alle Farben
				device.setColor("" + redS + greenS + blueS);

				// 25 - W
				payload.position(pos + 25);
				byte alpha = payload.get();
				testPrint("25", alpha);

				// 26 - Name 1...
				ByteBuffer tmpBuf = payload.duplicate();
				tmpBuf.position(pos + 26);
				tmpBuf.limit(pos + 26 + 16);
				CharBuffer nameBuf = charset.decode(tmpBuf);

				String name = nameBuf.toString().trim();
				device.setName(name);

				devices.add(device);
				

			}`

**Comment by jens-maus** [comment]
Das OSRAM Lightify ja inzwischen angekündigt/eingestellt ist gibt es hier leider nichts mehr zu machen/hinzuzufügen.
