### ISSUE TITLE
mastervalue gibt ungültiges XML zurück

### ISSUE THREAD

**Issue by dkern** [homematic-community/XML-API#19]
Hallo,

ich habe ein Problem mit der `mastervalue`. Wenn ich hier mein Gerät aufrufen möchte (Temperatursensor) wird ein ungültiges XML zurückgegeben. Beispiel:

> /addons/xmlapi/mastervalue.cgi?device_id=1337

```XML
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mastervalue>
  <device name='Temperatursensor Außen' ise_id='1337' device_type='HmIP-STHO-A' >
```

Dort endet das XML Dokument, genau so. In anderen Abfragen, wie `state.cgi` habe ich mit der `device_id=1337` keine Probleme.

**Comment by dwellmann** [comment]
Hallo,
gibt es da neue Infos zu, habe XML-API - Versioin 1.20 und den selben Fehler hier?

**Comment by dkern** [comment]
Ich denke mal die Erweiterung wird nicht mehr aktiv entwickelt, nachdem hier 2 Jahre nichts passiert ist.

**Comment by jens-maus** [comment]
@dkern Na dann los! Entwickle sie weiter!

**Comment by dkern** [comment]
Ne danke, nachdem das nach 25 Monaten die einzige Reaktion ist eher nicht. 😉

**Comment by jens-maus** [comment]
Hat dich vor 25 Monaten schon niemand davon abgehalten der homematic-community gruppe beizutreten und Eigeninitiative zu zeigen. Das hier ist nämlich ein community projekt! Also einfach mal machen statt einzufordern...

**Comment by dkern** [comment]
Woher kommt die Einstellung, dass jeder der Fehler meldet dieses auch selbst beheben soll (und kann), und wo war der Einwand vor zwei Jahren?! Und überhaupt, was ist jetzt dein Problem? Das ich angemerkt habe, dass hier allgemein lange nichts passiert ist?

Naja, wegen mir, ich mach das dann nun zu hier. Mir ist es eh egal, ich verwende die API nicht mehr.

**Comment by Monty1979** [comment]
Was soll hier auch passieren? Die XML-API habe ich vor Jahren mal weiterentwickelt weil ich für meine App noch paar Daten von der CCU brauchte. Jens hat dann das Thema übernommen und weiter Funktionen  / Anpassungen gemacht. 
Fakt ist bei mir läuft die API 100% und ich sehe keinen Bedarf was anzupassen. Ich denke mal da Jens oder die anderen Entwickler nichts mehr angepasst haben, haben sie auch keine Fehler.
Wenn du jetzt einen Fehler mit deinem HmIP-STHO-A hast, dann pass doch bitte die API an oder lebe mit dem Fehler ;-)

**Comment by dkern** [comment]
Das ist wirklich das Beste an Reaktionen, welche ich je auf GitHub zu einem Issue erlebt habe. Muss die deutsche Mentalität sein. 😉 

> Was soll hier auch passieren? Die XML-API habe ich vor Jahren mal weiterentwickelt weil ich für meine App noch paar Daten von der CCU brauchte. Jens hat dann das Thema übernommen und weiter Funktionen / Anpassungen gemacht. Fakt ist bei mir läuft die API 100% und ich sehe keinen Bedarf was anzupassen. Ich denke mal da Jens oder die anderen Entwickler nichts mehr angepasst haben, haben sie auch keine Fehler.

Der Erste kommt und sagt, man solle eventuelle Probleme selbst lösen, und nun kommt der zweite Entwickler mit "wenn es bei mir läuft gibt es keine Fehler". Grandios. 😄 Dann schließt doch die Issues gleich oder schreibt einen Hinweis mit "unsere Software ist Fehlerfrei und wenn ihr doch was findet macht es alleine". Denn jeder mit einem Problem ist natürlich auch Entwickler. Wieso dann überhaupt öffentlich machen?!

> Wenn du jetzt einen Fehler mit deinem HmIP-STHO-A hast, dann pass doch bitte die API an oder lebe mit dem Fehler ;-)

Wie du alleine hier schon siehst, scheine ich nicht der Einzige mit dem Problem (gewesen) zu sein. Und garantiert meldet sich nicht jeder bei Fehlern hier. Auch hat hier niemand etwas "eingefordert", wie Kollege Maus sich gleich aufregte. Aber wofür soll ein Issue-Management denn sonst da sein, wenn nicht zum melden von Fehlern?! Wenn man sich hier schon daran stört, das jemand Fehler meldet ohne sie selbst zu beheben. Aber sei es drum, du wirst den letzten Beitrag vermutlich nicht ganz gelesen haben, denn mittlerweile verwende ich die API nicht mehr, denn da gab es auch noch anderen Probleme. Auch wenn bei euch alles läuft. 😉 

Ist aber nach wie vor interessant, dass es zwei Jahre keinerlei Reaktion in irgendeiner Weise und keine Anpassung überhaupt (neben der readme) gibt, und wenn dann jemand schreibt, ich glaube an dem Projekt passiert nichts mehr, dann kommen direkt zwei Entwickler und echauffieren sich ...

**Comment by jens-maus** [comment]
> Das ist wirklich das Beste an Reaktionen, welche ich je auf GitHub zu einem Issue erlebt habe. Muss die deutsche Mentalität sein. 😉
[...]
>  Auch hat hier niemand etwas "eingefordert", wie Kollege Maus sich gleich aufregte.

Ich hab mich nicht aufgeregt, sondern bin lediglich darauf eingestiegen nachdem du mit recht deutlichem Kommentar gestichelt hattest, dass hier die letzten zwei Jahre nix passiert ist und du es aber nicht einsiehst hier selbst hand an zu legen. Das einzige worauf ich aufmerksam gemacht habe ist, das das hier ein Community Projekt ist und wenn du einen Fehler hier meldest, sich aber eben nix tut liegt das vielleicht nicht daran, das das Projekt obsolet oder eingestellt ist, sondern vielleicht daran das entweder kein anderer das Problem hat oder die anderen Entwickler/Interessierten andere Probleme bzw. Prioritäten haben. Und ab dann ist eben Eigeninitiative angebracht wenn man schon über eigenes Entwicklungs-KnowHow verfügt. Und wenn man das nicht tut oder eben seine eigene Zeit zu schade dafür ist, dann sollte man IMHO besser ruhig sein als solch einen offensichtlich provozierenden Kommentar abzugeben, denn offensichtlich ist/war dir zumindest für das diskutieren hier nicht die Zeit zu schade...

> Aber wofür soll ein Issue-Management denn sonst da sein, wenn nicht zum melden von Fehlern?! Wenn man sich hier schon daran stört, das jemand Fehler meldet ohne sie selbst zu beheben.

Darum geht es nicht und Fehlermeldungen sind weiterhin erwünscht und gewollt. Nur sollte man eben nicht erwarten das das Issue Management hier einer TODO Liste gleich kommt die ein Entwickler abzuarbeiten hat.

> Aber sei es drum, du wirst den letzten Beitrag vermutlich nicht ganz gelesen haben, denn mittlerweile verwende ich die API nicht mehr, denn da gab es auch noch anderen Probleme. Auch wenn bei euch alles läuft. 😉

Auch das könnte man kritisch sehen. Statt selbst hand anzulegen und versuchen dinge so zu verbessern das auch andere profitieren ist es leider inzwischen auch Gang und Gebe das man als API Nomade dann eben weiterzieht und schnell mal auf eine andere API wechselt damit man selbst seine eigene Zeit vermeintlich effektiver nutzen kann. Das ist natürlich vollkommen legitim und OK, aber dann sollte man erst recht zweimal darüber nachdenken ob man hingeht und andere dafür kritisiert das sie es nicht geschafft haben in den letzten zwei Jahren Zeit für jemand anderen zu opfern.

> Ist aber nach wie vor interessant, dass es zwei Jahre keinerlei Reaktion in irgendeiner Weise und keine Anpassung überhaupt (neben der readme) gibt, und wenn dann jemand schreibt, ich glaube an dem Projekt passiert nichts mehr, dann kommen direkt zwei Entwickler und echauffieren sich ...

Das ist wie gesagt die Reaktion auf deine IMHO sehr provokante Art&Weise der diskussion darüber das hier 2 jahre aus deiner sicht nichts passiert ist. Eben einfach mal den Ball bisschen flacher halten und sich dann nicht darüber wundern das es so laut zurückschallt wie man in den Wald hineinbrüllt...

**Comment by dkern** [comment]
Eine Sache scheinst du aber auch nicht zu verstehen: ich habe nichts gefordert noch habe ich hier nachgefragt, eine Erwartungshaltung gezeigt, Druck gemacht, noch war es für mich weiter Relevant, was ihr aus der Fehlermeldung meinerseits macht. Meine einzige Reaktion galt der anderen Person, welche sich hier nach dem Stand erkundigt hat und ob es etwas Neues gibt. Darauf zu antworten, dass hier allgemein seit zwei Jahren nichts passiert ist, ist weder provokant, noch gestichelt, noch sonst etwas. Das ist in meinen Augen absolut legitim. Provokant wurde es ab deiner Antwort à la "dann mach doch selbst weiter".

Aus meiner Antwort also zu lesen, dass es mich irgendwie interessiert hat, ob ihr reagiert, den Fehler behebt oder eben nicht, liegt somit alleine in deinem Ermessen, aber nicht in meinen Aussage. Genauso wie nur du verstehen kannst, wieso du bei der Feststellung direkt provoziert fühlst und "losbrüllst" (um bei deiner Wortwahl zu bleiben).

**Comment by Monty1979** [comment]
Das ist ein Community Projekt Projekt!
Wenn was nicht läuft dann spiel nicht uns den Ball zu sondern mach es selber oder falls du es nicht kannst, gilt auch für andere User, bitte uns dich dabei zu unterstützen.

" verwende ich die API nicht mehr"
Das ist natürlich auch eine Alternative.

**Comment by dkern** [comment]
> Das ist ein Community Projekt Projekt!

Das ist doch schön für die Community. Und was hat das damit zu tun, dass ein User, der nicht zur Community gehört. einen Fehler meldet? Es ist doch lachhaft, das melden von Fehlern damit zu verknüpfen es selbst zu lösen. Natürlich meldet man Probleme an die Entwickler, ganz egal ob es ein Einzelner, eine Firma oder eine Community ist. Und natürlich spielt man euch "den Ball dann zu". Wem sonst?! Und sag jetzt nicht wieder man soll es selbst machen ...

> gilt auch für andere User, bitte uns dich dabei zu unterstützen

Schau mal in die Issues. Es gibt mehrere Nutzer die hier Fehler/Probleme melden, die sich scheinbar extra nur dafür bei GitHub angemeldet haben. Wenn ihr (die Community) nicht mal in der Lage seid zu kommunizieren und die Leute auch darauf hinzuweisen oder in Kontakt zu treten (und das sogar mehrere Jahre lang), woher sollen diese Leute dann wissen, dass das eure Einstellung ist?! Immerhin gehen gerade diese Leute, ja schon mit der Anmeldung aktiv auch euch zu. Verlang jetzt nicht noch, dass ich mir eine Glaskugel anschaffe. 😉 Ihr scheint ja auch genug Zeit für Diskussionen und Sticheleien gegen User zu haben, da scheinen 1-2 Sätze in Issues ja auch nicht zu viel zu sein. Oder legt halt eine Contribution-Datei an, damit jeder Bescheid weiß.

Und bitte hör du (oder besser ihr) auf, die beleidigte Leberwurst zu spielen, weil ein USER euch als ENTWICKLER eine (oder mehrere) Probleme mit eurer Software meldet und nach zwei Jahren jemand anderem antwortet, dass hier wohl nichts mehr passiert. Auch einer Community sollte daran gelegen sein, das zu lösen und zwar ohne den Leuten noch Vorwürfe zu machen, sie würden es nicht selbst in die Hand nehmen. Und wie gesagt, versteh mich nicht falsch, ich habe nie etwas gefordert noch Vorwürfe gemacht. Aber verlange du auch nicht von mir, das ich mich darum kümmere Bugs in der Community-Software zu fixen oder mich weiter damit zu beschäftigen. Das ist genauso meine Entscheidung, wie es eure ist zu antworten oder eben nicht. Aber bitte habt dann auch kein Problem damit, wenn man sagt, hier passiert nichts. Ohne euch das vorzuwerfen ist das alles worüber ihr euch gerade aufregt, doch das Resultat aus fehlender Aktivität und mangelnder Kommunikation. Also ärgert euch auch nicht, wenn es jemand erwähnt.

Ich habe an so vielen öffentlichen Projekten, auch auf der Entwicklerseite und auch in größeren Community getriebenen Projekten mitgearbeitet, aber so eine Erwartungshaltung habe ich noch nicht erlebt. Natürlich gibt es auch fordernde User, ohne Frage. Aber die Grundeinstellung eines Entwicklers oder Entwicklergruppe ist für mich absolut neu und euer Umgang absolut ungerechtfertigt.

**Comment by dwellmann** [comment]
Moin zusammen,
so einen Thread wollte ich mit meiner Frage aber nicht losgetreten haben. Ok, bin selber Softwareentwickler, hier fast alles zu lesen kostet vermutlich soviel Zeit, dass ich es auch selber hättte lösen können - vermutlich -. Habe nächste Woche etwas Zeit, dann mache ich ein Issue auf und werde wohl auch die Lösung liefern. Community-Projekte haben mir schon viel Zeit gespart, so it's Payback-Time.

**Comment by dkern** [comment]
Und darum lösche ich das jetzt auch. Möge die Community das regeln. 😉
