### ISSUE TITLE
Sonderzeichen in Attributen werden nicht korrekt codiert

### ISSUE THREAD

**Issue by sidamos** [homematic-community/XML-API#27]
/addons/xmlapi/protocol.cgi

<row datetime="2019-02-10 11:15:16" names="CCU SV Push Text" values="<font color=orange>Servicemeldung!</font><br/>- Waschmaschine: Konfigurationsdaten stehen zur Übertragung an." timestamp="1549793716" />

Die <> im Attribut "values" müssten als &lt; bzw. &gt; codiert werden.

**Comment by jens-maus** [comment]
Bitte konkretes Beispiel geben/zeigen und zeigen wie es angeblich "richtiger" sein sollte.

**Comment by sidamos** [comment]
Github hat meinen Text verändert. Mal probieren, ob es jetzt klappt.

Die Servicemeldung ist "<font color=orange>Servicemeldung!</font><br/>- Waschmaschine: Konfigurationsdaten stehen zur Übertragung an.".
Das ist legal und funktioniert.

Wenn man jetzt protocol.cgi aufruft, dann erhält mal illegales XML:
``
<row datetime="2019-02-10 11:15:16" names="CCU SV Push Text" values="<font color=orange>Servicemeldung!</font><br/>- Waschmaschine: Konfigurationsdaten stehen zur Übertragung an." timestamp="1549793716" />
``
error on line 20 at column 70: Unescaped '<' not allowed in attributes values

Korrekt wäre:
``
<row datetime="2019-02-10 11:15:16" names="CCU SV Push Text" values="&lt;font color=orange&gt;Servicemeldung!&lt;/font&gt;&lt;br/&gt;- Waschmaschine: Konfigurationsdaten stehen zur Übertragung an." timestamp="1549793716" />
``

Siehe u.a. hier: https://stackoverflow.com/questions/5709232/how-do-i-include-etc-in-xml-attribute-values

**Comment by jens-maus** [comment]
@sidamos Da hast du natürlich vollkommen recht. Allerdings passiert das nur weil du den entsprechenden Skript hast der deine "CCU SV Push Text" variable mit html Codes füllt. Standardmäßig passiert sowas nicht auf einer Vanille CCU bzw. RaspberryMatic. Es ist aber richtig das hier die Funktion entsprechend die html tags ersetzen sollte

**Comment by sidamos** [comment]
Beides korrekt.
