### ISSUE TITLE
Link in der Zusatzsoftware Ansicht in einem neuen Tab öffnen

### ISSUE THREAD

**Issue by LevelOne2k** [homematic-community/XML-API#37]
Hallo!

Bitte hier den Link in einem neuen Tab öffnen wenn man drauf klickt. Bisher öffnet er sich im gleichen Fenster.

Danke!

<img width="795" alt="Bildschirmfoto 2020-01-09 um 02 39 20" src="https://user-images.githubusercontent.com/25386824/72030516-80246a80-3289-11ea-8bb6-5a8f70bb8893.png">

**Comment by HookHM** [comment]
@jens-maus kann das bitte berücksichtigt werden. Hatte auch gehofft das es in der 1.21 mit drin ist, leider nicht. Wenn Der Link im selben Fenster geöffnet wird, verlässt man zugleich logischerweise die WebUI der CCU und wenn man zurück navigiert, kommt diese Meldung
<img width="443" alt="Bildschirmfoto 2021-07-11 um 15 43 25" src="https://user-images.githubusercontent.com/55434236/125197652-e0211600-e25e-11eb-81ec-94cbcab76d80.png">

**Comment by jens-maus** [comment]
Das ist ein Feature das es automatisch in RaspberryMatic aber nicht in der CCU3 WebUI gibt und gehört nicht in die Zuständigkeit des Addons. Folglich gibt es hier nichts zu verbessern, sondern bitte auf RaspberryMatic wechseln wenn das gewünscht ist.
