### ISSUE TITLE
statechange.cgi funktioniert mit CCU Version 2.51.6 nicht mehr

### ISSUE THREAD

**Issue by mquasten** [homematic-community/XML-API#39]
Nachdem ich die eq3 Firmeware von 2,47.15 auf 2.51.6 aktualisiert habe funktioniert
statechange.cgi nicht mehr. Nachdem ich dann wieder auf die alte Firmeware Version gewechselt bin, funktioniert alles wieder wie vorher.

Es wird ein HTTP-Code: 411 Length Required zurückgegeben

The HyperText Transfer Protocol (HTTP) 411 Length Required client error response code indicates that the server refuses to accept the request without a defined Content-Length header.

Im Moment bin ich wieder zu der funktionierenden Version 2.47.15 zurück gewechselt. Die XML-API macht das ganze nämlich für mich erst wirklich nutzbar, das  meiste von eq3  würde ich  ehr als "konvergent" bezeichnen  (monton und beschränkt). Die XML API will ich unbedingt weiter nutzen und es wäre auch nicht schlecht wieder aktuelle Firmeware Versionen verwenden zu können, wenn denn eq3 doch mal nicht zu erwartende Singularitäten bieten sollte... 

Ich verwende eine CCU2 als Hardware (leider nur eine und da ich dann recht schnell zur alten Version zurück bin, kann ich auch keine wirkliche Fehleranalyse betreiben).   Die verwendete Version der xml-Api ist 1.20. 
[log.txt](https://github.com/jens-maus/XML-API/files/4308589/log.txt)

**Comment by Monty1979** [comment]
hallo ich hatte den selben Fehler. zieh mal bitte die CCU wieder hoch auf die 2.51.6 und installier danach die XMl-API nochmals. Dann sollte es laufen

**Comment by mquasten** [comment]
Hallo,

ich hab‘s probiert, der alte Fehler:

Hier  der ClientCode (ist Java, aber das ist relativ egal) :

final Collection<String> values = states.stream().map(state -> state.getValue()).collect(Collectors.toList());
		parameter.put(ID_PARAMETER_NAME,  StringUtils.collectionToCommaDelimitedString(ids));
		parameter.put(VALUE_PARAMETER_NAME, StringUtils.collectionToCommaDelimitedString(values));

		final ResponseEntity<String> res = webClientBuilder().build().put().uri(uri, parameter).exchange().block(timeout).toEntity(String.class).block(timeout);
		
		if (!StringUtils.hasText(res.getBody())) {
			throw newHttpStatusCodeException(HttpStatus.BAD_REQUEST, "Result expected.");
		}
		
		httpStatusGuard(res);

Zurück  kommt ein HTTP-CODE 411 :   https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411
Genutzt wird die Schnittstelle wie folgt : Übergeben werden durch Komma getrennt ids und werte der zu ändernden ich glaube hier konkret ausschließlich  SystemVaiablen.  An der Stelle httpStatusGuard(res) knallt es dann, weil nichts mit 2xx sondern 411 zurück kommt. 

Als Fehlermeldung sehe ich 411 Length Required, was aber auch nichts hilft, weil es nur die ist, die zu dem http Code gehört.

Vielleicht muss ich  den Mist mal mit curl oder im Browser nachstellen, aber ich bin mir eigentlich relativ sicher  auch da http 411.

Soblad ich die alte Version wieder installiere, alles ok.

Schöne Grüße 

Manfred 
 

Gesendet von Mail für Windows 10

Von: Maik B.
Gesendet: Mittwoch, 15. Juli 2020 14:57
An: jens-maus/XML-API
Cc: mquasten; Author
Betreff: Re: [jens-maus/XML-API] statechange.cgi funktioniert mit CCU Version2.51.6 nicht mehr (#39)

hallo ich hatte den selben Fehler. zieh mal bitte die CCU wieder hoch auf die 2.51.6 und installier danach die XMl-API nochmals. Dann sollte es laufen
