### ISSUE TITLE
Fehler bei state.cgi

### ISSUE THREAD

**Issue by Gerti1972** [homematic-community/XML-API#43]
Rufe ich mehrere Zustände über die state.cgi auf, kommt es unter Umständen zu einer Fehlermeldung.

```
This page contains the following errors:
error on line 1 at column 52: Extra content at the end of the document
Below is a rendering of the page up to the first error.
```

Dieser Aufruf führt z.B. zu dieser Fehlermeldung:
http://192.168.2.30/config/xmlapi/state.cgi?datapoint_id=6415,30105,6416,18198,4414,3410,1834,3837,1482,1481,1483,22263,29784,16348,16349,22006,4381,4415

Lösche ich nur eine der IDs aus dem Aufruf (egal welche), erfolgt eine korrekte Anzeige der XML-Datei.

**Comment by jens-maus** [comment]
Welcher Browser wird hier verwendet? Ich kann das mit Chrome hier zuindest nicht reproduzieren und kann quasi eine (fast) unendliche Liste von ids angeben und das XML dokument bleibt vollkommen valide. Bitte daher mal einen anderen Browser verwenden. Es kann sein das es mitunter daran liegt das das Ergebnis das XMLAPI zurückgibt alles in einer einzelnen Zeile erzeugt wird und bei einer großen anzahl von IDs die XML ausgabe in einer Zeile an irgendwelche Line limits im Browser stößst. Das müsste man dann mitunter näher analysieren und ggf. Linebreaks in die Ausgabe machen damit solche Browser (welcher ist das?) damit klar kommen.

**Comment by Gerti1972** [comment]
Der Browser scheint egal zu sein.
Egal ob Chrome, Edge oder eine PCP-Klasse, es kommt zu diesem Fehler.

**Comment by Monty1979** [comment]
ich bekomme den selben Fehler in allen Browsern auf der CCU2. Scheinbar liegt es an der Zeichenlänge von 97 wenn man ein Zeichen entfernt geht es.

**Comment by jens-maus** [comment]
@Gerti1972 Wie gesagt, ich bekomm das hier mit Chrome nicht reproduziert, auch nicht mit kommandozeilen tools wie `curl`. Kannst du das bitte mal mit einem `curl` aufruf versuchen zu reproduzieren und die möglichen Fehlerausgabe hier präsentieren. Das wäre wirklich hilfreich.

**Comment by Gerti1972** [comment]
Der Fehler kommt zustande, da die Rückgabe nur das hier beinhaltet:
`<?xml version="1.0" encoding="ISO-8859-1" ?><state>`
Er kommt auch zustande, sobald die Länge der Eingabe entsprechend ist (wie Monty1979 schon angemerkt hat).
Selbst http://192.168.2.30/config/xmlapi/state.cgi?datapoint_id=667333010536416318198344143341031834338373148231481314833222633297843163483163493220063438134415 führt zu diesem Fehler.
Die Tests wurden mit einer original CCU3 gemacht, ggf. tritt der Fehler bei Raspberrymatic nicht auf?!

**Comment by jens-maus** [comment]
@Gerti1972 Danke, das kann ich nun zumindest reproduzieren das es da zu probleme kommt mit solch einer falschen `datapoint_id`. Kannst du bitte dann mal in deine `/var/log/messages` Datei auf der CCU3 nach ScriptRunTimeErrornn ausschau halten. Denn dort sollte auch geloggt werden wenn du mit deiner langen liste von validen IDs versuchst die state.cgi aufzurufen. vielleicht gibts da dann einen hinweis.

**Comment by jens-maus** [comment]
@Gerti1972 Uiuiui, du scheinst auf einen tieferen Bug entweder in der ReGaHss oder an anderer Stelle in der CCU gestoßen zu sein :) der unabhängig vom XMLAPI Addon zu sein scheint, wie es aussieht  Denn probier mal folgenden Skript unter "Skript testen" auszuführen:

```
string aaaaaaaaaaaaa = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
WriteLine("ENDE");
```

Weder in der WebUI noch in der RemoteAPI Auführung führt das zum erfolg und es wird weder unter `/var/log/messages` ein Fehler ausgegeben, noch gibt er `ENDE` am schluss aus. Interessanterweise kann man nun entweder bei `aaaaaaaaaaaaa` ein beliebiges Zeichen anhängen oder wegmachen oder auch in dem langen `bbbbbb` inhalt des strings. Auch da kann man ein zeichen weglassen oder hinzufügen und schon funktioniert der Skript. Hier stinkt etwas ganz gewaltig und noch weiss ich nicht ganz was genau. Momentane Vermutung ist ein Bug direkt in ReGaHss....

**Comment by jens-maus** [comment]
Wie im referenzierten und inzwische geschlossenen Ticket im RaspberryMatic Projekt vermerkt konnte ich das Problem in der Tat auf einen Bug in ReGaHss zurückführen. Das Problem wurde auch bereits prinzipiell beseitigt und sollte ab der ReGaHss version R1.00.0388.0221 nicht mehr auftreten (wird vmtl. in die nächste kommende RaspberryMatic Version integriert werden). Bis dahin werde ich diese Ticket hier entsprechend offen halten.
