### ISSUE TITLE
Falsche Timestamps bei Homematic IP Komponenten

### ISSUE THREAD

**Issue by 5NineN** [homematic-community/XML-API#48]
Der Timestamp für State (und andere) ist bei Homematic IP Komponenten (HMIP-DRS4, HMIP-DRS8, HMIP-PSM, + evtl. weitere) nur innerhalb der ersten 4500 Sekunden richtig, danach erfolgt eine Aktualisierung aller Timestamps, obwohl es keine Änderung gegeben hat. Somit ist der Zeitpunkt einer letzten Änderung nicht mehr einsehbar. Die Timestamps in der CCU3 Weboberfläche hingegen sind korrekt.

Der Aufruf von z.B. http://ccu3/config/xmlapi/state.cgi?device_id=60714 liefert den Output (s.u.). Dabei ist schon auffällig, dass die meisten Timestamps exakt 1604389499 (+/- 1) betragen. Das Problem tritt nicht sofort auf, aber zuverlässig nach ca. 4500 Sekunden, da dann eine Aktualisierung aller Timestamps erfolgt. Woher genau diese falsche Timestamps stammen ist mir unklar, da die Timestamps, welche über die Weboberfläche der CCU3 einsehbar sind, korrekt sind. Auch die Deaktivierung von zyklischen Statusmeldungen behebt das Problem nicht:

`
<state>
<device name="Garage-HmIPW-DRS8 serial" ise_id="60714" unreach="false" config_pending="false">
<channel name="Garage-HmIPW-DRS8 serial:0" ise_id="60715">
<datapoint name="HmIP-RF.serial:0.ACTUAL_TEMPERATURE" type="ACTUAL_TEMPERATURE" ise_id="60716" value="10.000000" valuetype="4" valueunit="°C" timestamp="1604389498"/>
<datapoint name="HmIP-RF.serial:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="60717" value="false" valuetype="2" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:0.ERROR_CODE" type="ERROR_CODE" ise_id="60721" value="0" valuetype="8" valueunit="" timestamp="1604389498"/>
<datapoint name="HmIP-RF.serial:0.ERROR_OVERHEAT" type="ERROR_OVERHEAT" ise_id="60722" value="false" valuetype="2" valueunit="" timestamp="1604389498"/>
<datapoint name="HmIP-RF.serial:0.ERROR_UNDERVOLTAGE" type="ERROR_UNDERVOLTAGE" ise_id="60726" value="false" valuetype="2" valueunit="" timestamp="1604389498"/>
<datapoint name="HmIP-RF.serial:0.IDENTIFICATION_MODE_KEY_VISUAL" type="IDENTIFICATION_MODE_KEY_VISUAL" ise_id="60730" value="" valuetype="2" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:0.IDENTIFICATION_MODE_LCD_BACKLIGHT" type="IDENTIFICATION_MODE_LCD_BACKLIGHT" ise_id="60731" value="" valuetype="2" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:0.IDENTIFY_DURATION" type="IDENTIFY_DURATION" ise_id="60732" value="" valuetype="4" valueunit="s" timestamp="0"/>
<datapoint name="HmIP-RF.serial:0.IDENTIFY_TARGET_LEVEL" type="IDENTIFY_TARGET_LEVEL" ise_id="60733" value="" valuetype="4" valueunit="100%" timestamp="0"/>
<datapoint name="HmIP-RF.serial:0.OPERATING_VOLTAGE" type="OPERATING_VOLTAGE" ise_id="60735" value="24.200000" valuetype="4" valueunit="V" timestamp="1604389498"/>
<datapoint name="HmIP-RF.serial:0.OPERATING_VOLTAGE_STATUS" type="OPERATING_VOLTAGE_STATUS" ise_id="60736" value="0" valuetype="16" valueunit="" timestamp="1604389498"/>
<datapoint name="HmIP-RF.serial:0.UNREACH" type="UNREACH" ise_id="60737" value="false" valuetype="2" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="60741" value="false" valuetype="2" valueunit="" timestamp="1603822804"/>
</channel>
<channel name="HmIPW-DRS8 serial:1" ise_id="60745">
<datapoint name="HmIP-RF.serial:1.PROCESS" type="PROCESS" ise_id="60746" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:1.SECTION" type="SECTION" ise_id="60747" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:1.SECTION_STATUS" type="SECTION_STATUS" ise_id="60748" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:1.STATE" type="STATE" ise_id="60749" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="Garage Außenlicht" ise_id="60750">
<datapoint name="HmIP-RF.serial:2.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60751" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:2.PROCESS" type="PROCESS" ise_id="60753" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:2.SECTION" type="SECTION" ise_id="60754" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:2.SECTION_STATUS" type="SECTION_STATUS" ise_id="60755" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:2.STATE" type="STATE" ise_id="60756" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:3" ise_id="60757">
<datapoint name="HmIP-RF.serial:3.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60758" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:3.PROCESS" type="PROCESS" ise_id="60760" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:3.SECTION" type="SECTION" ise_id="60761" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:3.SECTION_STATUS" type="SECTION_STATUS" ise_id="60762" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:3.STATE" type="STATE" ise_id="60763" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:4" ise_id="60764">
<datapoint name="HmIP-RF.serial:4.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60765" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:4.PROCESS" type="PROCESS" ise_id="60767" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:4.SECTION" type="SECTION" ise_id="60768" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:4.SECTION_STATUS" type="SECTION_STATUS" ise_id="60769" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:4.STATE" type="STATE" ise_id="60770" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:5" ise_id="60771">
<datapoint name="HmIP-RF.serial:5.PROCESS" type="PROCESS" ise_id="60772" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:5.SECTION" type="SECTION" ise_id="60773" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:5.SECTION_STATUS" type="SECTION_STATUS" ise_id="60774" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:5.STATE" type="STATE" ise_id="60775" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="Garten (Doppelsteckdose Terasse)" ise_id="60776">
<datapoint name="HmIP-RF.serial:6.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60777" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:6.PROCESS" type="PROCESS" ise_id="60779" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:6.SECTION" type="SECTION" ise_id="60780" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:6.SECTION_STATUS" type="SECTION_STATUS" ise_id="60781" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:6.STATE" type="STATE" ise_id="60782" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:7" ise_id="60783">
<datapoint name="HmIP-RF.serial:7.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60784" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:7.PROCESS" type="PROCESS" ise_id="60786" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:7.SECTION" type="SECTION" ise_id="60787" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:7.SECTION_STATUS" type="SECTION_STATUS" ise_id="60788" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:7.STATE" type="STATE" ise_id="60789" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:8" ise_id="60790">
<datapoint name="HmIP-RF.serial:8.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60791" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:8.PROCESS" type="PROCESS" ise_id="60793" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:8.SECTION" type="SECTION" ise_id="60794" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:8.SECTION_STATUS" type="SECTION_STATUS" ise_id="60795" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:8.STATE" type="STATE" ise_id="60796" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:9" ise_id="60797">
<datapoint name="HmIP-RF.serial:9.PROCESS" type="PROCESS" ise_id="60798" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:9.SECTION" type="SECTION" ise_id="60799" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:9.SECTION_STATUS" type="SECTION_STATUS" ise_id="60800" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:9.STATE" type="STATE" ise_id="60801" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="Garten (Terassenlampen)" ise_id="60802">
<datapoint name="HmIP-RF.serial:10.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60803" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:10.PROCESS" type="PROCESS" ise_id="60805" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:10.SECTION" type="SECTION" ise_id="60806" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:10.SECTION_STATUS" type="SECTION_STATUS" ise_id="60807" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:10.STATE" type="STATE" ise_id="60808" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:11" ise_id="60809">
<datapoint name="HmIP-RF.serial:11.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60810" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:11.PROCESS" type="PROCESS" ise_id="60812" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:11.SECTION" type="SECTION" ise_id="60813" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:11.SECTION_STATUS" type="SECTION_STATUS" ise_id="60814" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:11.STATE" type="STATE" ise_id="60815" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:12" ise_id="60816">
<datapoint name="HmIP-RF.serial:12.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60817" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:12.PROCESS" type="PROCESS" ise_id="60819" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:12.SECTION" type="SECTION" ise_id="60820" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:12.SECTION_STATUS" type="SECTION_STATUS" ise_id="60821" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:12.STATE" type="STATE" ise_id="60822" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:13" ise_id="60823">
<datapoint name="HmIP-RF.serial:13.PROCESS" type="PROCESS" ise_id="60824" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:13.SECTION" type="SECTION" ise_id="60825" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:13.SECTION_STATUS" type="SECTION_STATUS" ise_id="60826" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:13.STATE" type="STATE" ise_id="60827" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="Garten (Licht) - out of order" ise_id="60828">
<datapoint name="HmIP-RF.serial:14.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60829" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:14.PROCESS" type="PROCESS" ise_id="60831" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:14.SECTION" type="SECTION" ise_id="60832" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:14.SECTION_STATUS" type="SECTION_STATUS" ise_id="60833" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:14.STATE" type="STATE" ise_id="60834" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:15" ise_id="60835">
<datapoint name="HmIP-RF.serial:15.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60836" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:15.PROCESS" type="PROCESS" ise_id="60838" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:15.SECTION" type="SECTION" ise_id="60839" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:15.SECTION_STATUS" type="SECTION_STATUS" ise_id="60840" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:15.STATE" type="STATE" ise_id="60841" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:16" ise_id="60842">
<datapoint name="HmIP-RF.serial:16.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60843" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:16.PROCESS" type="PROCESS" ise_id="60845" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:16.SECTION" type="SECTION" ise_id="60846" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:16.SECTION_STATUS" type="SECTION_STATUS" ise_id="60847" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:16.STATE" type="STATE" ise_id="60848" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:17" ise_id="60849">
<datapoint name="HmIP-RF.serial:17.PROCESS" type="PROCESS" ise_id="60850" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:17.SECTION" type="SECTION" ise_id="60851" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:17.SECTION_STATUS" type="SECTION_STATUS" ise_id="60852" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:17.STATE" type="STATE" ise_id="60853" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="Garten (Zisternenpumpe)" ise_id="60854">
<datapoint name="HmIP-RF.serial:18.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60855" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:18.PROCESS" type="PROCESS" ise_id="60857" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:18.SECTION" type="SECTION" ise_id="60858" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:18.SECTION_STATUS" type="SECTION_STATUS" ise_id="60859" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:18.STATE" type="STATE" ise_id="60860" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:19" ise_id="60861">
<datapoint name="HmIP-RF.serial:19.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60862" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:19.PROCESS" type="PROCESS" ise_id="60864" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:19.SECTION" type="SECTION" ise_id="60865" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:19.SECTION_STATUS" type="SECTION_STATUS" ise_id="60866" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:19.STATE" type="STATE" ise_id="60867" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:20" ise_id="60868">
<datapoint name="HmIP-RF.serial:20.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60869" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:20.PROCESS" type="PROCESS" ise_id="60871" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:20.SECTION" type="SECTION" ise_id="60872" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:20.SECTION_STATUS" type="SECTION_STATUS" ise_id="60873" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:20.STATE" type="STATE" ise_id="60874" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:21" ise_id="60875">
<datapoint name="HmIP-RF.serial:21.PROCESS" type="PROCESS" ise_id="60876" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:21.SECTION" type="SECTION" ise_id="60877" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:21.SECTION_STATUS" type="SECTION_STATUS" ise_id="60878" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:21.STATE" type="STATE" ise_id="60879" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:22" ise_id="60880">
<datapoint name="HmIP-RF.serial:22.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60881" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:22.PROCESS" type="PROCESS" ise_id="60883" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:22.SECTION" type="SECTION" ise_id="60884" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:22.SECTION_STATUS" type="SECTION_STATUS" ise_id="60885" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:22.STATE" type="STATE" ise_id="60886" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:23" ise_id="60887">
<datapoint name="HmIP-RF.serial:23.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60888" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:23.PROCESS" type="PROCESS" ise_id="60890" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:23.SECTION" type="SECTION" ise_id="60891" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:23.SECTION_STATUS" type="SECTION_STATUS" ise_id="60892" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:23.STATE" type="STATE" ise_id="60893" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:24" ise_id="60894">
<datapoint name="HmIP-RF.serial:24.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60895" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:24.PROCESS" type="PROCESS" ise_id="60897" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:24.SECTION" type="SECTION" ise_id="60898" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:24.SECTION_STATUS" type="SECTION_STATUS" ise_id="60899" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:24.STATE" type="STATE" ise_id="60900" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:25" ise_id="60901">
<datapoint name="HmIP-RF.serial:25.PROCESS" type="PROCESS" ise_id="60902" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:25.SECTION" type="SECTION" ise_id="60903" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:25.SECTION_STATUS" type="SECTION_STATUS" ise_id="60904" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:25.STATE" type="STATE" ise_id="60905" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="Garage Innenlicht" ise_id="60906">
<datapoint name="HmIP-RF.serial:26.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60907" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:26.PROCESS" type="PROCESS" ise_id="60909" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:26.SECTION" type="SECTION" ise_id="60910" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:26.SECTION_STATUS" type="SECTION_STATUS" ise_id="60911" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:26.STATE" type="STATE" ise_id="60912" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:27" ise_id="60913">
<datapoint name="HmIP-RF.serial:27.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60914" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:27.PROCESS" type="PROCESS" ise_id="60916" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:27.SECTION" type="SECTION" ise_id="60917" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:27.SECTION_STATUS" type="SECTION_STATUS" ise_id="60918" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:27.STATE" type="STATE" ise_id="60919" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:28" ise_id="60920">
<datapoint name="HmIP-RF.serial:28.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60921" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:28.PROCESS" type="PROCESS" ise_id="60923" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:28.SECTION" type="SECTION" ise_id="60924" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:28.SECTION_STATUS" type="SECTION_STATUS" ise_id="60925" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:28.STATE" type="STATE" ise_id="60926" value="false" valuetype="2" valueunit="" timestamp="1604389499"/>
</channel>
<channel name="HmIPW-DRS8 serial:29" ise_id="60927">
<datapoint name="HmIP-RF.serial:29.PROCESS" type="PROCESS" ise_id="60928" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:29.SECTION" type="SECTION" ise_id="60929" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:29.SECTION_STATUS" type="SECTION_STATUS" ise_id="60930" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:29.STATE" type="STATE" ise_id="60931" value="false" valuetype="2" valueunit="" timestamp="1604389500"/>
</channel>
<channel name="Garage Tor" ise_id="60932">
<datapoint name="HmIP-RF.serial:30.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60933" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:30.PROCESS" type="PROCESS" ise_id="60935" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:30.SECTION" type="SECTION" ise_id="60936" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:30.SECTION_STATUS" type="SECTION_STATUS" ise_id="60937" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:30.STATE" type="STATE" ise_id="60938" value="false" valuetype="2" valueunit="" timestamp="1604389500"/>
</channel>
<channel name="HmIPW-DRS8 serial:31" ise_id="60939">
<datapoint name="HmIP-RF.serial:31.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60940" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:31.PROCESS" type="PROCESS" ise_id="60942" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:31.SECTION" type="SECTION" ise_id="60943" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:31.SECTION_STATUS" type="SECTION_STATUS" ise_id="60944" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:31.STATE" type="STATE" ise_id="60945" value="false" valuetype="2" valueunit="" timestamp="1604389500"/>
</channel>
<channel name="HmIPW-DRS8 serial:32" ise_id="60946">
<datapoint name="HmIP-RF.serial:32.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60947" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:32.PROCESS" type="PROCESS" ise_id="60949" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:32.SECTION" type="SECTION" ise_id="60950" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:32.SECTION_STATUS" type="SECTION_STATUS" ise_id="60951" value="0" valuetype="16" valueunit="" timestamp="1604389500"/>
<datapoint name="HmIP-RF.serial:32.STATE" type="STATE" ise_id="60952" value="false" valuetype="2" valueunit="" timestamp="1604389500"/>
</channel>
<channel name="HmIPW-DRS8 serial:33" ise_id="60953">
<datapoint name="HmIP-RF.serial:33.COMBINED_PARAMETER" type="COMBINED_PARAMETER" ise_id="60954" value="" valuetype="20" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:33.WEEK_PROGRAM_CHANNEL_LOCKS" type="WEEK_PROGRAM_CHANNEL_LOCKS" ise_id="60955" value="0" valuetype="16" valueunit="" timestamp="1604389499"/>
<datapoint name="HmIP-RF.serial:33.WEEK_PROGRAM_TARGET_CHANNEL_LOCK" type="WEEK_PROGRAM_TARGET_CHANNEL_LOCK" ise_id="60956" value="" valuetype="16" valueunit="" timestamp="0"/>
<datapoint name="HmIP-RF.serial:33.WEEK_PROGRAM_TARGET_CHANNEL_LOCKS" type="WEEK_PROGRAM_TARGET_CHANNEL_LOCKS" ise_id="60957" value="" valuetype="16" valueunit="" timestamp="0"/>
</channel>
</device>
</state>
`

**Comment by 5NineN** [comment]
Duplicate

**Comment by jens-maus** [comment]
Duplicate of #47
