### ISSUE TITLE
Fehler bei Installation in Home Assistant Raspberrymatic Add On

### ISSUE THREAD

**Issue by jutonium** [homematic-community/XML-API#56]
RaspberryMatic Version: 3.59.6.20210807
Home Assistant (Supervised):
Core 2021.8.3
Supervisor: 2021.06.8

Installation schlägt fehl mit folgender Meldung:
"Error 102
Ein unerwarteter Fehler ist während der Addon-Installation aufgetreten.
Bei der hochgeladenen Datei handelt es sich entweder nicht um ein Addon-Archiv, ist defekt oder ist für eine andere Hardware vorgesehen.
Bitte versuchen Sie es erneut oder kontaktieren Sie den Autor des Addons."

Thema im HomeMatic-Forum: https://homematic-forum.de/forum/viewtopic.php?f=65&t=69013&p=674190#p674190

**Comment by king1979** [comment]
Bei mir liegt das selbe Problem vor.

Meine Versionen lauten:
RaspberryMatic Version: 3.59.6.20210807
Home Assistant (Supervised): Core 2021.8.4
Supervisor: 2021.06.8

**Comment by jens-maus** [comment]
Das ist kein Problem dieses XML-API Addons, sondern der aktuellen RaspberryMatic 3.59.6.20210807 version. Also bitte dort ein entsprechendes Ticket dazu aufmachen.
