### ISSUE TITLE
XML-API 1.21 - Info-Feld in sysvarlist.cgi fehlt (geklärt)

### ISSUE THREAD

**Issue by erikno2** [homematic-community/XML-API#58]
Hi, hab mal auf 1.21. upgedatet
und siehe da meine ganze Web-Oberfläche die xmlapi verwendet funktioniert nicht mehr, da das Info-Feld in der sysvarlist.cgi nicht mehr mitgeliefert wird.
- Ist das passiert oder war das Absicht.
- Im Code der sysvarlist.cgi sehe ich aber keinen Unterschied zu früher

LG

**Comment by erikno2** [comment]
SORRY, habe mal gegraben und festgestellt dass ich meine xml-api scheinbar mal erweitert habe. Und ein Update haut das natürlich raus.
Meine Erweiterung: Das Script sysvarlist.cgi bzw. sysvar.cgi liefert von der CCU nicht alle Werte. Im Teil
```
...
foreach (sSysVarId, dom.GetObject(ID_SYSTEM_VARIABLES).EnumUsedIDs()) {
		oSysVar     = dom.GetObject(sSysVarId);
      ...
                Write("' type='"); WriteXML( oSysVar.ValueType());
                Write("' subtype='"); WriteXML( oSysVar.ValueSubType());
                ...
                Write("' logged='"); WriteXML( oSysVar.DPArchive());
                Write("' visible='"); WriteXML( oSysVar.Visible()); 
```
wird z.B. nicht die Beschreibung der Systemvariablen mitgeliefert. Durch Einfügen der Zeile

`Write("' info='"); WriteXML( oSysVar.DPInfo());`

kann das erweitert werden.
Dumm nur dass ich nicht bedacht habe, dass ich das immer nach einem Update wieder einbauen muss.
Sorry

**Comment by jens-maus** [comment]
Dann mach daraus doch ein PullRequest damit das ggf mit aufgenommen werden kann.
