### ISSUE TITLE
Generic Error (TIMEOUT) beim Setzen von HM-WTH2 Profilen

### ISSUE THREAD

**Issue by n300home** [homematic-community/XML-API#61]
Hallo zusammen, 

Seit einigen Wochen beobachte ich Probleme beim (Batch)Umschalten von 11 Raumthermostaten auf ein anderes Profil via Redmatic. Raspimatik, Redmatic sowio die XML-API sind auf der latest Release.
![image](https://user-images.githubusercontent.com/25461480/156533639-7496578b-8b07-4a10-8c2d-f63951689c09.png)
Es ist nicht so, dass alle der 11 fehlschlagen, aber ca. die hälfte macht er, dann fängt es an zu haken. 
Hier meine CCU Konfig in Redmatic:
![image](https://user-images.githubusercontent.com/25461480/156534151-77848fd7-b97f-4c35-bc04-05117aa499b0.png)

**Comment by jens-maus** [comment]
Kann ich leider nicht reproduzieren.
