### ISSUE TITLE
Exclude NO_SERVICEMSG entries in systemNotification.cgi

### ISSUE THREAD

**Issue by HolgerJeromin** [homematic-community/XML-API#62]
We can exclude service messages in the webgui since:
https://github.com/jens-maus/RaspberryMatic/issues/222
https://github.com/jens-maus/RaspberryMatic/commit/88c03303f2967978bd3758feb089a2da44d44ec0
But I still see `type="UNREACH"` messages in `systemNotification.cgi` of XML-API and I do not found a marker in `deviceList.cgi` to add filtering...

**Comment by jens-maus** [comment]
The feature to disable service messages for certain devices (i.e. `NO_SERVICEMSG`) is a pure RaspberryMatic WebUI feature where this flag allows to suppress these service messages. Thus, there is currently no way/plan to transfer this to XML-API.
