### ISSUE TITLE
TinyMatic Sync-Issue since 1.21?

### ISSUE THREAD

**Issue by kangaroo72** [homematic-community/XML-API#65]
Hi,

I'm not using it, but a friend contacted me, and I tried also.
We're using Tinymatic (Android App). Since the update from 1.20 to 1.21 the App is no longer syncing with CCU / RaspberryMatic.
Is this a known issue?

Best regards.

**Comment by HolgerJeromin** [comment]
Does downgrade helps?

**Comment by kangaroo72** [comment]
No. Already tried 😔

**Comment by HolgerJeromin** [comment]
I meant downgrade of xml-api to 1.20. 
If this does not work I would try to contact TinyMatic vendor. Perhaps the underlying Android had some changed behavior in an update.

**Comment by ultrah** [comment]
Do you get any error message? Might be related to an addon that is not compatible. Some addons put data into system variables for example that is not valid XML.
