### ISSUE TITLE
Problem with comma separated value

### ISSUE THREAD

**Issue by uniforx** [homematic-community/XML-API#66]
Hi .. i will call a url like this to set a Hue to a special color:

http://<IP>/addons/xmlapi/statechange.cgi?ise_id=123,456&new_value=0.5,rgb(255,255,0,255)

But this command results in an red bulb because after the "rgb(255" the requests ends. I tried to encode like rgb(255%2C... but still without success.

**Comment by HolgerJeromin** [comment]
>  I tried to encode like rgb(255%2C... but still without success.

Because on the wire the string is already encoded:
```
'%2Fstatechange.cgi%3Fise_id%3D123%2C456%26new_value%3D0.5%2Crgb(255%2C255%2C0%2C255)'
```
The internal parsing has to be smarter when it gets a `(` char.

**Comment by uniforx** [comment]
Now I have looked at the code and found out that there is a definition for RGB values, which means that RGB values always have to be sent as a separate call without multiple comma separated value lists. The exception for RGB values must occur after the splitting and not as an exception condition before it? 

I can read the code but I´m not familiar with CGI/Pearl and I don´t know how to setup an development environment for local testing.

Is somebody able to solve this issue? Here is a dirty solution but backward compatible. I would send the rgb values seperated by semicolon instead of comma.

`if { [string match "rgb*" $new_value ]} {
	array set res [rega_script "Write(dom.GetObject($ise_id).State('$new_value'));"]

	if {$res(STDOUT) != "null"} {
		puts -nonewline "<changed id=\"$ise_id\" new_value=\"$new_value\" />";
	} else {
		puts -nonewline "<not_found />";
	}
	
} else {

	set rec_new_value [split $new_value "\,"]
	set rec_ise_id [split $ise_id "\,"]

	for {set x 0} {$x<[llength $rec_ise_id]} {incr x} {

	  if { [string match "rgb*" [lindex $rec_new_value $x] ]} {
	    regsub -all {;} [lindex $rec_new_value $x] {,} [lindex $rec_new_value $x]
    }

    array set res [rega_script "Write(dom.GetObject([lindex $rec_ise_id
    } $x]).State('[lindex $rec_new_value $x]'));"]

    if {$res(STDOUT) != "null"} {
      puts -nonewline "<changed id=\"[lindex $rec_ise_id $x]\" new_value=\"[lindex $rec_new_value $x]\" />";
    } else {
      puts -nonewline "<not_found />";
    }
	}
}`

**Comment by jens-maus** [comment]
implemented in XML-API v2
