### ISSUE TITLE
HmIP-WRC2 & HmIP-WRCR not reporting values

### ISSUE THREAD

**Issue by ThisIsTenou** [homematic-community/XML-API#67]
Hey, upon trying to integrate HmIP-WRC2 & HmIP-WRCR devices into my HomeAssistant/NodeRed setup, I had to discover that events such as button presses / turns don't seem to be actually processed.
This prevents me from using these devices with systems outside of the Homematic Ecosystem, which unfortunatly is the exact purpose I bought them for.
Is this something fixable, or are there reasons for this to not be a thing yet?

**Comment by jens-maus** [comment]
Wrong project I am afraid. XML-API has nothing to do with HomeAssistant functionality and event delivery.
