### ISSUE TITLE
Keine Nutzung von TinyMatic mit XML-API v2 mehr möglich

### ISSUE THREAD

**Issue by zaphod2** [homematic-community/XML-API#75]
Ich habe in TinyMatic mit dem XML-CCU Addon 2.0 keinerlei Anzeige mehr. wie soll ich es beschreiben. eine Synchronisation wird ohne eine Fehlermeldung scheinbar durchgeführt, aber die Anzeige der Räume, Programme, Systemvariablen u.s.w. bleibt leer.
Die Widgets auf dem Android-Bildschirm sind dann auch ohne Inhalt.
Ich kann es zumindest reproduzieren mit der v.1.22 und der v.2.0

**Comment by jens-maus** [comment]
> Ich habe in TinyMatic mit dem XML-CCU Addon 2.0 keinerlei Anzeige mehr.

Das ist (leider) normal. Die in der Version 2 der XML-API umgesetzten Sicherheitsverbesserungen machen es notwendig, dass zwingende Anpassungen an Anwendungen vorgenommen werden damit diese die neue Version 2 der XML-API wieder unterstützen. Die steht so übrigens auch im Changelog als :warning: Breaking Change :warning: Hinweis.

Im Falle von TinyMatic (das ja voll und ganz auf XML-API setzt) ist es nun leider auch noch zusätzlich so, dass der Autor @ultrah wohl leider entschieden hat das vormals quelloffene Projekt (früher https://github.com/ultrah/TinyMatic) komplett zu wieder von GitHub zu entfernen und es auch noch an einen Drittanbieter zu verkaufen der selbst eine andere HomeMatic App kommerziell vertreibt :( (cf https://homematic-forum.de/forum/viewtopic.php?p=780663#p780663) Insofern stehe die Chancen wohl leider sehr sehr niedrig das TinyMatic jemals an die XML-API v2 angepasst wird und man sollte TinyMatic ehrlich gesagt wohl lieber als tote Applikation einstufen.

**Comment by zaphod2** [comment]
Danke, das wusste ich natürlich nicht und hatte mich heute nur gewundert warum das nun auch nicht mehr geht.
Aber so ist das scheinbar, erst Geld und dann "ach wir pflegen doch nicht unsere App"

**Comment by ultrah** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=80&t=80190&p=780712#p780712

**Comment by jens-maus** [comment]
@ultrah 
> https://homematic-forum.de/forum/viewtopic.php?f=80&t=80190&p=780712#p780712

Danke für die Erläuterungen. Aber auch hier bei GitHub möchte ich es noch einmal verewigen, dass ich das aus der Sicht der HomeMatic / CCU Community sehr sehr traurig finde das du diese Schritt gegangen bist und denke das damit früher oder später keinerlei Android-basierte App mehr zur Verfügung stehen wird, ganz einfach deshalb weil jsmatic sich mit ihrem kommerziellen Cloud-Modell irgendwann genauso wie andere Cloud-Modelle nicht mehr tragen wird. Und schade finde ich auch das damit all deine jahrelange Arbeit an TinyMatic mittelfristig für die Tonne war.

Hättest du TinyMatic unter eine echten, robusten OpenSource Lizenz einfach freigegeben hätte sich schon jemand gefunden der die Arbeit im besten Falle sogar als kostenlose App weitergeführt hätte. So stehe die CCU Nutzer mit Android Geräten nun leider fast komplett auf dem Trockenen wenn Sie die Finger von einem Cloud-Produkt wie jsmatic lassen wollen...

**Comment by Johann1388** [comment]
@jens-maus 
Danke für deine Einschätzung, aber das ist nicht ganz so wie du es hier schreibst.

Wir haben Tinymatic übernommen mit der Intention die App weiter zu pflegen.
jsmatic an sich ist eine reine Homematic CCU App die nichts mit einem Clouddienst zu tun hat. 
Den Clouddienst(JSMatic Connect) kann man sich zusätzlich holen, sowie zum Beispiel Cloudmatic. 
Die Unterstützung des XML Addons 2.0 werden wir auch sehr zeitnah umsetzen.

**Comment by jens-maus** [comment]
@Johann1388 
Danke für die schnelle Klarstellung. Dann hoffen wir ihr könnt dir Anpassungen für XML-API v2 schnell umsetzen und die CCU/RaspberyMatic Community bzgl. TinyMatic Aufkauf auch wieder etwas beruhigen helfen. Hier wären vielleicht Announcements und eine Roadmap zu dem Thema TinyMatic sicherlich eine gute Idee. Und wenn eine so kommerziell agierende Firma wie die deine sich vielleicht auch im Thema Sponsoring von OpenSource Projekten – von denen Sie nicht unwesentlich profitieren – etwas mehr engagieren könnte würde das sicherlich auch helfen Hürden abzubauen.

**Comment by jens-maus** [comment]
Da neuere Versionen von TinyMatic nun mit Kompatibilität zur XML-API v2 kommen kann ich denke ich mal zugemacht werden..
