### ISSUE TITLE
programactions.cgi not working as expected after bugfix #80

### ISSUE THREAD

**Issue by smezger123** [homematic-community/XML-API#84]
Thank you for fixing programactions.cgi in issue #80

But it´s still not working as expected. Even if you pass active=false in the URL, the program will be set to active=true (and same on setting visible)

http://192.168.1.xx/addons/xmlapi/programlist.cgi?sid=xxxxxx&program_id=6746&active=false&visible=false

**Comment by jens-maus** [comment]
Well. it was only fix in the repo yet and not yet released, thus is not part of XML-API v2.2.

**Comment by smezger123** [comment]
Yes, for sure. But i don´t want to wait for 2.4 until it´s finally working.

```
    string active = "} $active {";
    ...
    obj.Active(active);
```

active is now a string. Even the string value "false" will be casted to (bool)true

Thanks a lot!

**Comment by jens-maus** [comment]
So what is the outcome now of this issue ticket here? Does the new `programactions.cgi` from the master branch works now for you or not? Because IMHO https://github.com/homematic-community/XML-API/blob/master/xmlapi/programactions.cgi#L34-L41 should work correctly. If not, point out the issue or submit a PR.

**Comment by jens-maus** [comment]
@smezger123 
Ok, after wiping out your sarcasm from your last comment I understood what you mean and I think commit https://github.com/homematic-community/XML-API/commit/34e674441a417f7691011d97ba161263df29a6d3 should fix the issue. If not, open a new issue and explain in detail and without sarcasm or any other misleading comments. Thx for the hint.

**Comment by Maik2208** [comment]
Hi @jens-maus 
is the change really intended as implemented? Active and visible should be hard "true", regardless of wether "true" or "false" was passed?

**Comment by jens-maus** [comment]
I think the change is intended yes. The point is that active is a string variable (have to be) but the `obj.Active()` function requires a `boolean` as @smezger123 pointed out. Thus the `obj.Active(active == "true")` line should perfectly convert the "true" string to a boolean and then pass that to the `Active()` function.

**Comment by Maik2208** [comment]
Sorry, of course! My mistake
