### ISSUE TITLE
Ein HmIP-SM55-2 liefert im XML keinen Helligkeitswert, obwohl dieser im UI angezeigt wird.

### ISSUE THREAD

**Issue by drose28357** [homematic-community/XML-API#85]
TinyMatic zeigt mir für einen (!!) Bewegungsmelder HmIP-SM55i-2 keine Helligkeitswerte an. Für einen gleichartigen Bewegungsmelder werten Werte angezeigt.

Analyse: In XML 2.2 kann über statelist.cgi alle Statuswerte aller Geräte ausgegebene werden. Für den fraglichen Bewegungsmelder "BewM_Küche_Taster" wird der Value 0 zurück gegeben, obwohl im UI der Wert 11 (bzw. 6 als alter Wert in der Gewerke-Ansicht siehe Anlage) angezeigt wird. 

Da das schwierig nachzustellen ist, biete ich eine WebSession an, falls das etwas nutzt.

Siehe Anlagen:
UI-Wert in der Anlage "Ansicht_Bewegungsmelder_Bedienung_Geräte.png"
UI-Werte für einen zweiten HmIP-SMI-2 "BewM_Wohnzimmer" zum Vergleich in der Anlage "Ansicht_Bewegungsmelder_Gewerke.png"
UI-Auflistung der Bewegunsmelder mit ihren ID in "Ansicht_BewegungsmelderGeräteliste.png"
Ergebnis aus statelist.cgi mit hervorgehobenen Werten in Kanal drei der beiden Bewegungsmelder in  "Screenshot_Bewegungsmelder_satelist.cgi.png"
Vollständigen XML-Liste in "statelist.cgi.pdf"

<img width="1009" alt="Ansicht_Bewegungsmelder_Gewerke" src="https://github.com/homematic-community/XML-API/assets/11533286/cf5bd27e-4fb5-4508-97f9-dc7a0df7090d">
<img width="1078" alt="Ansicht_Bewegungsmelder_Bedienung_Geräte" src="https://github.com/homematic-community/XML-API/assets/11533286/32013841-b424-41d2-805b-07cb31725ddd">
<img width="1244" alt="Ansicht_BewegungsmelderGeräteliste" src="https://github.com/homematic-community/XML-API/assets/11533286/ed63e763-1565-494b-9f97-480af5501528">
<img width="1018" alt="Screenshot_Bewegungsmelder_satelist cgi" src="https://github.com/homematic-community/XML-API/assets/11533286/f57828c3-56dc-4edc-a126-09cd897099f4">
[statelist.cgi.pdf](https://github.com/homematic-community/XML-API/files/13317772/statelist.cgi.pdf)

Systemdaten:
Hardware Model:	Raspberry Pi 4 Model B Rev 1.1 (rpi4b2g)
Product:	raspmatic_rpi4 (3.71.12.20231020)
ReGaHss:	R1.00.0388.0235
Zusatzsoftware : XML-API 2.2

**Comment by drose28357** [comment]
Closed, da ich im XML den falschen Status ausgewerte habe. 
Relevant ist 
<datapoint name="HmIP-RF.00319F298AB44C:3.ILLUMINATION" type="ILLUMINATION" ise_id="63942" value="23.800000" valuetype="4" valueunit="" timestamp="1699608755" operations="5"/>

Hier wird der korrekte Weret aus dem UI ausgegeben.

Ich werde ein Ticket bei TinyMatic einstellen.

**Comment by jens-maus** [comment]
Bitte mal unter der CCU/RaspberryMatic DevConfig aktivieren und schauen welchen Wert der Datenpunkt `CURRENT_ILLUMINATION` dort aufweist. Wenn dort auch 0 angezeigt wird, dann liegt es nicht an der XML-API selbst.

Das "Problem" wird sein: Die WebUI zeigt den Wert des `ILLUMINATION` und nicht `CURRENT_ILLUMINATION` Datenpunktes an, da der `ILLUMINATION` Datenpunkt den Wert beinhaltet der über einen gewissen Zeitraum gemittelt wird. Diese Mittelung kann man in den Geräteeinstellungen des jeweiligen Gerätes einstellen/modifizieren und dann erhält `ILLUMINATION` eben den entsprechenden gemittelten Wert.

Problem ist/wird sein das TinyMatic einfach immer nur den Wert des `CURRENT_ILLUMINATION` Datenpunkten nutzt/anzeigt. Es sollte aber stattdessen `ILLUMINATION` nutzen damit die Geräteeinstellungen entsprechend mit berücksichtig werden.
