### ISSUE TITLE
Limit tokens to specific actions

### ISSUE THREAD

**Issue by stephandue** [homematic-community/XML-API#87]
Hi,

I would like to use the XML-API to change run a script on the CCU3. I would tell the bridge of another device the URL to trigger the program once the devices status has changed.

My problem is the security concept. The token of XML-Api is transferred in plain text. So if somebody is listening to the Requests in the local network one could obtain the token. For this particular function it's no problem as it only triggers the CCU to get the status of a device. But once the token is known it could be used to list all programs and trigger them.

So my question is if I could limit tokens to specific programs?

Many Thanks
Stephan

**Comment by jens-maus** [comment]
> My problem is the security concept. The token of XML-Api is transferred in plain text. So if somebody is listening to the Requests in the local network one could obtain the token. For this particular function it's no problem as it only triggers the CCU to get the status of a device. But once the token is known it could be used to list all programs and trigger them.
> 
> So my question is if I could limit tokens to specific programs?

No you can't. But if you are concerned about someone potentially grabbing your tokens from your URL requests against XML-API, simply make sure to only use HTTPS which will then also make sure that the URL requests will be transferred SSL encrypted, thus nobody being able to grab the token.

**Comment by stephandue** [comment]
Hi Jens,

thanks for your reply but my scenario is in a local network.

Best
Stephan

**Comment by jens-maus** [comment]
I know, but even in your local network you can use HTTPS encryption of course if you are serious about being concerned that someone is spying on your local network... On other hand, if you don't trust your local network setup, who else do you trust then?

**Comment by stephandue** [comment]
The bridge device unfortunately does not support HTTPS

**Comment by jens-maus** [comment]
Then you have the only option to use a token per application and in case you identify a mitigation of a certain token you manually revoke it. Apart from that I don't see any other solution.
