### ISSUE TITLE
xml-api answers with not_authenticated in v2.3

### ISSUE THREAD

**Issue by f1dot4** [homematic-community/XML-API#89]
When using the newest available xml-api 2.3, requests fail with
```
​​​​​​<result>
<not_authenticated/>
</result>​
```
I tested `statechange.cgi` and some additional ones as well.

After downgrading (uninstall/install) to previously installed xml-api 1.22, xml-api works again. 
No other settings were touched on CCU.

I found the issue on loxforum as well: https://www.loxforum.com/forum/faqs-tutorials-howto-s/135-homematic-fit-machen-f%C3%BCr-loxone/page2#post407454

I'm using RaspberryMatic docker container v3.71.12.20231020

Offtopic: Thanks for all your efforts (in general re the CCU project), you work is highly appreciated and saved a lot of heating-costs already last winter.

**Comment by jens-maus** [comment]
This is not a bug, but a feature!

Please read the explicit warning "⚠️ UPDATE NOTICE ⚠️ " text about breaking changes in the release notes of XML-API and make yourself familiar with XML-API v2 before you assume this might be a bug. See

https://github.com/homematic-community/XML-API/releases/tag/2.3

Bottom line:
YOU have to touch all XML-API calls yourself and add a security token which you first have to generate yourself. ergo, XML-API v2 requires changes made by the caller by adding sid=XXXXX security token parameters to every user case! thus, this is NO bug!
