### ISSUE TITLE
Falscher Content-Type bei einigen XML-API Funktionen

### ISSUE THREAD

**Issue by ChristianRiedl** [homematic-community/XML-API#90]
Bei einigen XML-API Funktionen 

- mastervalue.cgi
- checkuptodate.cgi
- favoritelist.cgi
- devicelist.cgi
- mastervaluechange.cgi

wird ein falscher ContentType (genau gesagt der Charset Teil) geliefert. XML encoding ist richtig. Man sieht das auch im Skript wie z.B

    puts "Content-Type: text/xml; charset=iso-8559-1"
    puts ""
    puts -nonewline "<?xml version='1.0' encoding='ISO-8859-1' ?>

Das kann dann bei strengen Konversionen  Stream -> Text zu Problemen führen.

**Comment by jens-maus** [comment]
Was soll an iso-8859-1 bitte falsch sein. Bitte Probleme aufzeigen.

**Comment by jens-maus** [comment]
> ISO-8859-1 entspricht Latin Alphabet no 1,das ist OK. Aber **iso-8559-1** gib es nicht :
> 
> puts "Content-Type: text/xml; charset=**iso-8559-1**"

Ah, nun sehe ich den typo auch :) good catch...
